server:
  port: 8085
spring:
  config:
    import: "optional:configserver:"
  application:
    name: userms-client
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
resilience4j:
  circuitbreaker:
    instances:
      userms:
        failure-rate-threshold: 50
        sliding-window-size: 6
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: count-based
        wait-duration-in-open-state: 10s
application:
  theme:
    color: "blue"
