server:
  port: 8087
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka, http://localhost:8761/eureka
  instance:
    appname: userms-client
    prefer-ip-address: true      
spring:
  application:
    name: userms-client
userms:
  service:
    name: USERMS          
management:
  tracing:
    sampling:
      probability: 1
  endpoint:
    health:
      enabled: true
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
resilience4j:
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      userms:
        failure-rate-threshold: 50  
        automatic-transition-from-open-to-half-open-enabled: true 
        wait-duration-in-open-state: 10s
        sliding-window-type: count-based
        sliding-window-size: 6
        minimum-number-of-calls: 8
        event-consumer-buffer-size: 10
  retry:
    retry-aspect-order: 2
    instances:
      userms:
        max-attempts: 3
        wait-duration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 5
logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]" 
  level: 
    '[com.nagarro.proxy]': debug
    '[com.nagarro.controller]': debug
  file:
    name: userclient-ws.log
limits-service: 8
      
       
